# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'rcarozu-sonar'
    organization: 'rcarozu-devsecops'
    scannerMode: 'MSBuild'
    projectKey: 'rcarozu-devsecops'
    projectName: 'rcarozu-DevSecOps'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: sonarcloud-buildbreaker@2
  inputs:
    SonarCloud: 'rcarozu-sonar'
    organization: 'rcarozu-devsecops'

- task: dependency-check-build-task@6
  inputs:
    projectName: 'pet-clinic'
    scanPath: '${Build.SourcesDirectory}/build/libs'
    format: 'HTML'

